# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_tutorial.ipynb.

# %% auto 0
__all__ = ['foo', 'test_tutorial']

# %% ../nbs/00_tutorial.ipynb 4
def foo():
    print('tutorial code is showing here')

# %% ../nbs/00_tutorial.ipynb 5
def test_tutorial():
    "Test if the tutorial is working correctly"
    return f'Hello : the tutorial is currently working'
